BETH_DIR  = ../..
DEPENDENCIES = ../bmath ../bcore

include $(BETH_DIR)/mk/lib.mk

CFLAGS  += `python3-config --embed --cflags` -Wno-sign-compare -Wno-comment
LDFLAGS += `python3-config --embed --ldflags`
