/** This file was generated by the beth-precode-compiler. Not suitable for manual editing.
 *
 *  Copyright and License:
 *      If a specification exists for the repository or folder in which the file is located,
 *      that specification shall apply. Otherwise, the Copyright and License of the associated
 *      source code files containing beth-precode shall apply.
 */

#include "bcore_precoded.h"
#include "bcore_spect_inst.h"
#include "bcore_const_manager.h"

// source: bcore_precoder_sample
#include "bcore_precoder_sample.h"
BCORE_DEFINE_OBJECT_INST( bcore_inst, bcore_precoder_sample_object_s ) "{ aware_t _; st_s name; sz_t => [] arr; } ";
BCORE_DEFINE_OBJECT_INST( bcore_inst, bcore_precoder_sample_object2_s ) "{ aware_t _; bcore_precoder_sample_object_s object; st_s name2; } ";

vd_t bcore_precoded_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "bcore_precoded" ) ) )
    {
        case TYPEOF_init1:
        {
            bcore_const_x_set_d( typeof( "bcore_precoded_hash" ), sr_tp( 698778841 ) );
            BCORE_REGISTER_OBJECT( bcore_precoder_sample_object_s );
            BCORE_REGISTER_OBJECT( bcore_precoder_sample_object2_s );
        }
        break;
        default: break;
    }
    return NULL;
}
