/** This file was generated by the beth-precode-compiler. Not suitable for manual editing.
 *
 *  Copyright and License:
 *      If a specification exists for the repository or folder in which the file is located,
 *      that specification shall apply. Otherwise, the Copyright and License of the associated
 *      source code files containing beth-precode shall apply.
 */

#ifndef BCORE_PRECODED_H
#define BCORE_PRECODED_H

#include "bcore_control.h"

// source: bcore_precoder_sample
#define TYPEOF_bcore_precoder_sample 933626240
#define TYPEOF_bcore_precoder_sample_object_s 1940901916
#define BETH_EXPAND_ITEM_bcore_precoder_sample_object_s BCORE_DECLARE_OBJECT( bcore_precoder_sample_object_s ) { aware_t _; st_s name; BCORE_ARRAY_DYN_LINK_STATIC_S( sz_t, arr_ ); };
#define TYPEOF_bcore_precoder_sample_object2_s 2687764618
#define BETH_EXPAND_ITEM_bcore_precoder_sample_object2_s BCORE_DECLARE_OBJECT( bcore_precoder_sample_object2_s ) { aware_t _; bcore_precoder_sample_object_s object; st_s name2; };
#define BETH_EXPAND_GROUP_bcore_precoder_sample \
    BETH_EXPAND_ITEM_bcore_precoder_sample_object_s \
    BETH_EXPAND_ITEM_bcore_precoder_sample_object2_s

vd_t bcore_precoded_signal_handler( const bcore_signal_s* o );

#endif // BCORE_PRECODED_H
