/** This file was generated by the plant-compiler.
 *
 *  Copyright and License:
 *    Code generated by the beth-plant compiler inherits the copyright and license
 *    of the beth-plant source code, which is contained in following files:
 *    bmath_f3.h
 *    bmath_mf3_sx.h
 *    bmath_mf3_sf.h
 *    bmath_hf3.h
 *    bmath_hf3_vm.h
 *
 */

#include "bmath_planted.h"
#include "bcore_spect.h"
#include "bcore_spect_inst.h"
#include "bcore_sr.h"
#include "bcore_const_manager.h"


/**********************************************************************************************************************/
// source: bmath_f3
#include "bmath_f3.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op

BCORE_DEFINE_SPECT( bmath_f3, bmath_f3_op )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_f3_op : get_arity;"
    "feature aware bmath_f3_op : ofx;"
    "feature aware bmath_f3_op : ogxi;"
    "feature aware bmath_f3_op : ogyi;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op_ar0

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar0_literal_s )
"aware bmath_f3_op_ar0"
"{"
    "f3_t v;"
    "func ^:f;"
    "func bmath_f3_op:get_arity;"
"}";

BCORE_DEFINE_SPECT( bmath_f3_op, bmath_f3_op_ar0 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_f3_op_ar0 : f;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op_ar1

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_zero_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_one_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_identity_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_exp_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_lgst_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_lgst_hard_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_lgst_leaky_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_tanh_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_tanh_hard_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_tanh_leaky_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_softplus_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_relu_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar1_leaky_relu_s )
"aware bmath_f3_op_ar1"
"{"
    "func ^:fx;"
    "func ^:gy;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogyi;"
"}";

BCORE_DEFINE_SPECT( bmath_f3_op, bmath_f3_op_ar1 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_f3_op_ar1 : fx;"
    "feature aware bmath_f3_op_ar1 : gy;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op_ar2

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar2_add_s )
"aware bmath_f3_op_ar2"
"{"
    "func ^:fx;"
    "func ^:gxa;"
    "func ^:gxb;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogxi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar2_sub_s )
"aware bmath_f3_op_ar2"
"{"
    "func ^:fx;"
    "func ^:gxa;"
    "func ^:gxb;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogxi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar2_mul_s )
"aware bmath_f3_op_ar2"
"{"
    "func ^:fx;"
    "func ^:gxa;"
    "func ^:gxb;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogxi;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_f3_op_ar2_div_s )
"aware bmath_f3_op_ar2"
"{"
    "func ^:fx;"
    "func ^:gxa;"
    "func ^:gxb;"
    "func bmath_f3_op:get_arity;"
    "func bmath_f3_op:ofx;"
    "func bmath_f3_op:ogxi;"
"}";

BCORE_DEFINE_SPECT( bmath_f3_op, bmath_f3_op_ar2 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_f3_op_ar2 : fx;"
    "feature aware bmath_f3_op_ar2 : gxa;"
    "feature aware bmath_f3_op_ar2 : gxb;"
"}";

/**********************************************************************************************************************/
// source: bmath_mf3_sx
#include "bmath_mf3_sx.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_mf3_sx

BCORE_DEFINE_OBJECT_INST_P( bmath_mf3_sx_s )
"aware bcore_inst"
"{"
    "sz_t slos;"
    "sz_t xons;"
    "sz_t rows;"
    "sz_t i_stride;"
    "sz_t [] i;"
    "f3_t [] v;"
"}";

/**********************************************************************************************************************/
// source: bmath_mf3_sf
#include "bmath_mf3_sf.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_mf3_sf

BCORE_DEFINE_OBJECT_INST_P( bmath_mf3_sf_s )
"aware bcore_inst"
"{"
    "sz_t cols;"
    "sz_t rows;"
    "sz_t i_stride;"
    "sz_t [] i;"
    "f3_t [] v;"
"}";

/**********************************************************************************************************************/
// source: bmath_hf3
#include "bmath_hf3.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_s )
"aware bcore_inst"
"{"
    "sz_t [] d;"
    "f3_t [] v;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_adl_s )
"aware bcore_array"
"{"
    "bmath_hf3_s => [];"
"}";

/**********************************************************************************************************************/
// source: bmath_hf3_vm
#include "bmath_hf3_vm.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_holor_s )
"aware bmath_hf3_vm"
"{"
    "tp_t name;"
    "tp_t type;"
    "bmath_hf3_s hf3;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_arr_holor_s )
"aware bcore_array"
"{"
    "bmath_hf3_vm_holor_s [];"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_prop_s )
"aware bmath_hf3_vm"
"{"
    "aware bmath_hf3_vm_op => op;"
    "private bmath_hf3_vm_s* p;"
    "func bcore_inst_call:copy_x;"
    "func bcore_via_call:mutated;"
    "func ^:run;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_proc_s )
"aware bcore_array"
"{"
    "tp_t name;"
    "bmath_hf3_vm_prop_s [];"
    "bcore_arr_sz_s in;"
    "bcore_arr_sz_s out;"
    "func bmath_hf3_vm:run;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_library_s )
"aware bcore_array"
"{"
    "bmath_hf3_vm_proc_s [];"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_frame_s )
"aware bmath_hf3_vm"
"{"
    "bmath_hf3_vm_arr_holor_s arr_holor;"
    "bmath_hf3_vm_library_s library;"
    "tp_t proc_setup = 0;"
    "tp_t proc_shelve = 0;"
    "bcore_hmap_tpuz_s map_proc;"
    "bcore_hmap_tpuz_s map_holor;"
    "bcore_hmap_name_s map_name;"
    "func ^:setup;"
    "func bcore_via_call:mutated;"
    "func bcore_via_call:shelve;"
"}";

BCORE_DEFINE_SPECT( bcore_inst, bmath_hf3_vm )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_hf3_vm : run;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op_ar0

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar0_determine_s )
"aware bmath_hf3_vm_op_ar0"
"{"
    "sz_t a;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
    "func bmath_hf3_vm_op_ar0:set_args;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar0_vacate_s )
"aware bmath_hf3_vm_op_ar0"
"{"
    "sz_t a;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
    "func bmath_hf3_vm_op_ar0:set_args;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar0_randomize_s )
"aware bmath_hf3_vm_op_ar0"
"{"
    "sz_t a;"
    "u2_t rseed = 1234;"
    "func ^:csetup_randomize;"
    "func bmath_hf3_vm:run;"
    "func bmath_hf3_vm_op_ar0:set_args;"
"}";

BCORE_DEFINE_SPECT( bmath_hf3_vm_op, bmath_hf3_vm_op_ar0 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_hf3_vm_op_ar0 : set_args;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op_ar1

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar1_linear_s )
"aware bmath_hf3_vm_op_ar1"
"{"
    "sz_t a;"
    "sz_t b;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
    "func bmath_hf3_vm_op_ar1:set_args;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar1_tanh_s )
"aware bmath_hf3_vm_op_ar1"
"{"
    "sz_t a;"
    "sz_t b;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
    "func bmath_hf3_vm_op_ar1:set_args;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar1_unary_s )
"aware bmath_hf3_vm_op_ar1"
"{"
    "sz_t a;"
    "sz_t b;"
    "bmath_fp_f3_unary unary;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
    "func bmath_hf3_vm_op_ar1:set_args;"
"}";

BCORE_DEFINE_SPECT( bmath_hf3_vm_op, bmath_hf3_vm_op_ar1 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_hf3_vm_op_ar1 : set_args;"
"}";

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op_ar2

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_add_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_add_s_set_args( bmath_hf3_vm_op_ar2_add_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_sub_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_sub_s_set_args( bmath_hf3_vm_op_ar2_sub_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_bmul_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_bmul_s_set_args( bmath_hf3_vm_op_ar2_bmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_bmul_htp_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_bmul_htp_s_set_args( bmath_hf3_vm_op_ar2_bmul_htp_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_htp_bmul_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_htp_bmul_s_set_args( bmath_hf3_vm_op_ar2_htp_bmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_htp_bmul_htp_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_htp_bmul_htp_s_set_args( bmath_hf3_vm_op_ar2_htp_bmul_htp_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_hmul_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_hmul_s_set_args( bmath_hf3_vm_op_ar2_hmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_mul_scl_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_mul_scl_s_set_args( bmath_hf3_vm_op_ar2_mul_scl_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_OBJECT_INST_P( bmath_hf3_vm_op_ar2_scl_mul_s )
"aware bmath_hf3_vm_op_ar2"
"{"
    "sz_t a;"
    "sz_t b;"
    "sz_t c;"
    "func ^:set_args;"
    "func ^:csetup;"
    "func bmath_hf3_vm:run;"
"}";

bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_scl_mul_s_set_args( bmath_hf3_vm_op_ar2_scl_mul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c )
{ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }

BCORE_DEFINE_SPECT( bmath_hf3_vm_op, bmath_hf3_vm_op_ar2 )
"{"
    "bcore_spect_header_s header;"
    "feature aware bmath_hf3_vm_op_ar2 : set_args;"
"}";

/**********************************************************************************************************************/

vd_t bmath_planted_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "bmath_planted" ) ) )
    {
        case TYPEOF_init1:
        {
            // Comment or remove line below to rebuild this target.
            bcore_const_x_set_d( typeof( "bmath_planted_hash" ), sr_tp( 2040926149 ) );
            BCORE_REGISTER_TRAIT( bmath_f3, bcore_inst );
            BCORE_REGISTER_FEATURE( bmath_f3_op_get_arity );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ofx );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ogxi );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ogyi );
            BCORE_REGISTER_SPECT( bmath_f3_op );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ar0_f );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar0_f, bmath_f3_op_ar0_literal_s_f );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar0_literal_s_get_arity );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar0_literal_s );
            BCORE_REGISTER_SPECT( bmath_f3_op_ar0 );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ar1_fx );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ar1_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_zero_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_zero_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_zero_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_zero_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_zero_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_zero_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_one_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_one_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_one_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_one_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_one_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_one_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_identity_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_identity_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_identity_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_identity_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_identity_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_identity_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_exp_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_exp_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_exp_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_exp_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_exp_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_exp_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_lgst_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_lgst_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_lgst_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_lgst_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_lgst_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_lgst_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_lgst_hard_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_lgst_hard_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_lgst_hard_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_lgst_hard_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_lgst_hard_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_lgst_hard_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_lgst_leaky_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_lgst_leaky_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_lgst_leaky_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_lgst_leaky_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_lgst_leaky_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_lgst_leaky_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_tanh_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_tanh_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_tanh_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_tanh_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_tanh_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_tanh_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_tanh_hard_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_tanh_hard_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_tanh_hard_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_tanh_hard_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_tanh_hard_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_tanh_hard_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_tanh_leaky_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_tanh_leaky_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_tanh_leaky_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_tanh_leaky_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_tanh_leaky_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_tanh_leaky_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_softplus_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_softplus_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_softplus_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_softplus_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_softplus_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_softplus_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_relu_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_relu_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_relu_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_relu_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_relu_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_relu_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_fx, bmath_f3_op_ar1_leaky_relu_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar1_gy, bmath_f3_op_ar1_leaky_relu_s_gy );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar1_leaky_relu_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar1_leaky_relu_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogyi, bmath_f3_op_ar1_leaky_relu_s_ogyi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar1_leaky_relu_s );
            BCORE_REGISTER_SPECT( bmath_f3_op_ar1 );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ar2_fx );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ar2_gxa );
            BCORE_REGISTER_FEATURE( bmath_f3_op_ar2_gxb );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_fx, bmath_f3_op_ar2_add_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxa, bmath_f3_op_ar2_add_s_gxa );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxb, bmath_f3_op_ar2_add_s_gxb );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar2_add_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar2_add_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogxi, bmath_f3_op_ar2_add_s_ogxi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar2_add_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_fx, bmath_f3_op_ar2_sub_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxa, bmath_f3_op_ar2_sub_s_gxa );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxb, bmath_f3_op_ar2_sub_s_gxb );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar2_sub_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar2_sub_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogxi, bmath_f3_op_ar2_sub_s_ogxi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar2_sub_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_fx, bmath_f3_op_ar2_mul_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxa, bmath_f3_op_ar2_mul_s_gxa );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxb, bmath_f3_op_ar2_mul_s_gxb );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar2_mul_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar2_mul_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogxi, bmath_f3_op_ar2_mul_s_ogxi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar2_mul_s );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_fx, bmath_f3_op_ar2_div_s_fx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxa, bmath_f3_op_ar2_div_s_gxa );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ar2_gxb, bmath_f3_op_ar2_div_s_gxb );
            BCORE_REGISTER_FFUNC( bmath_f3_op_get_arity, bmath_f3_op_ar2_div_s_get_arity );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ofx, bmath_f3_op_ar2_div_s_ofx );
            BCORE_REGISTER_FFUNC( bmath_f3_op_ogxi, bmath_f3_op_ar2_div_s_ogxi );
            BCORE_REGISTER_OBJECT( bmath_f3_op_ar2_div_s );
            BCORE_REGISTER_SPECT( bmath_f3_op_ar2 );
            BCORE_REGISTER_OBJECT( bmath_mf3_sx_s );
            BCORE_REGISTER_TRAIT( bmath_mf3_sx, bcore_inst );
            BCORE_REGISTER_OBJECT( bmath_mf3_sf_s );
            BCORE_REGISTER_TRAIT( bmath_mf3_sf, bcore_inst );
            BCORE_REGISTER_OBJECT( bmath_hf3_s );
            BCORE_REGISTER_OBJECT( bmath_hf3_adl_s );
            BCORE_REGISTER_TRAIT( bmath_hf3, bcore_inst );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_holor_s );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_arr_holor_s );
            BCORE_REGISTER_FEATURE( bmath_hf3_vm_run );
            BCORE_REGISTER_FFUNC( bcore_inst_call_copy_x, bmath_hf3_vm_prop_s_copy_x );
            BCORE_REGISTER_FFUNC( bcore_via_call_mutated, bmath_hf3_vm_prop_s_mutated );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_prop_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_prop_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_proc_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_proc_s );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_library_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_setup, bmath_hf3_vm_frame_s_setup );
            BCORE_REGISTER_FFUNC( bcore_via_call_mutated, bmath_hf3_vm_frame_s_mutated );
            BCORE_REGISTER_FFUNC( bcore_via_call_shelve, bmath_hf3_vm_frame_s_shelve );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_frame_s );
            BCORE_REGISTER_SPECT( bmath_hf3_vm );
            BCORE_REGISTER_TRAIT( bmath_hf3_vm_op, bmath_hf3_vm );
            BCORE_REGISTER_FEATURE( bmath_hf3_vm_op_ar0_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar0_csetup, bmath_hf3_vm_op_ar0_determine_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar0_determine_s_run );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar0_set_args, bmath_hf3_vm_op_ar0_determine_s_set_args );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar0_determine_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar0_csetup, bmath_hf3_vm_op_ar0_vacate_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar0_vacate_s_run );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar0_set_args, bmath_hf3_vm_op_ar0_vacate_s_set_args );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar0_vacate_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar0_csetup_randomize, bmath_hf3_vm_op_ar0_randomize_s_csetup_randomize );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar0_randomize_s_run );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar0_set_args, bmath_hf3_vm_op_ar0_randomize_s_set_args );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar0_randomize_s );
            BCORE_REGISTER_SPECT( bmath_hf3_vm_op_ar0 );
            BCORE_REGISTER_FEATURE( bmath_hf3_vm_op_ar1_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar1_csetup, bmath_hf3_vm_op_ar1_linear_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar1_linear_s_run );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar1_set_args, bmath_hf3_vm_op_ar1_linear_s_set_args );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar1_linear_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar1_csetup, bmath_hf3_vm_op_ar1_tanh_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar1_tanh_s_run );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar1_set_args, bmath_hf3_vm_op_ar1_tanh_s_set_args );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar1_tanh_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar1_csetup, bmath_hf3_vm_op_ar1_unary_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar1_unary_s_run );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar1_set_args, bmath_hf3_vm_op_ar1_unary_s_set_args );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar1_unary_s );
            BCORE_REGISTER_SPECT( bmath_hf3_vm_op_ar1 );
            BCORE_REGISTER_FEATURE( bmath_hf3_vm_op_ar2_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_add_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_add_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_add_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_add_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_sub_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_sub_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_sub_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_sub_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_bmul_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_bmul_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_bmul_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_bmul_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_bmul_htp_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_bmul_htp_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_bmul_htp_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_bmul_htp_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_htp_bmul_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_htp_bmul_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_htp_bmul_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_htp_bmul_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_htp_bmul_htp_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_htp_bmul_htp_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_htp_bmul_htp_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_htp_bmul_htp_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_hmul_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_hmul_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_hmul_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_hmul_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_mul_scl_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_mul_scl_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_mul_scl_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_mul_scl_s );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_set_args, bmath_hf3_vm_op_ar2_scl_mul_s_set_args );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_op_ar2_csetup, bmath_hf3_vm_op_ar2_scl_mul_s_csetup );
            BCORE_REGISTER_FFUNC( bmath_hf3_vm_run, bmath_hf3_vm_op_ar2_scl_mul_s_run );
            BCORE_REGISTER_OBJECT( bmath_hf3_vm_op_ar2_scl_mul_s );
            BCORE_REGISTER_SPECT( bmath_hf3_vm_op_ar2 );
        }
        break;
        default: break;
    }
    return NULL;
}
