/** This file was generated by the beth-plant-compiler.
 *
 *  Copyright and License:
 *    Generated code inherits the copyright and license of the beth-plant source code.
 *    The following files contain all source code related to this file:
 *    bmath_f3_op.h
 *    bmath_mf3_sx.h
 *    bmath_mf3_sf.h
 *    bmath_hf3.h
 *    bmath_hf3_op.h
 *    bmath_hf3_vm.h
 *
 */

#ifndef BMATH_PLANTED_H
#define BMATH_PLANTED_H

#include "bcore_control.h"


/**********************************************************************************************************************/
// source: bmath_f3_op.h

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op

#define TYPEOF_bmath_f3_op 3697762467
#define TYPEOF_bmath_f3_op_s 3885432133
#define BETH_EXPAND_GROUP_bmath_f3_op \
  BCORE_FORWARD_OBJECT( bmath_f3_op ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar2 ); \
  typedef sz_t (*bmath_f3_op_get_arity)( const bmath_f3_op* o ); \
  typedef f3_t (*bmath_f3_op_ofx)( const bmath_f3_op* o, const f3_t* a ); \
  typedef f3_t (*bmath_f3_op_ogxi)( const bmath_f3_op* o, const f3_t* a, sz_t i ); \
  typedef f3_t (*bmath_f3_op_ogyi)( const bmath_f3_op* o, const f3_t* a, sz_t i ); \
  BCORE_DECLARE_SPECT( bmath_f3_op ) \
  { \
      bcore_spect_header_s header; \
      bmath_f3_op_get_arity get_arity; \
      bmath_f3_op_ofx ofx; \
      bmath_f3_op_ogxi ogxi; \
      bmath_f3_op_ogyi ogyi; \
  }; \
  static inline bmath_f3_op* bmath_f3_op_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_f3_op, t ); return ( bmath_f3_op* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_f3_op_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_f3_op ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_f3_op ) \
  static inline bl_t bmath_f3_op_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_f3_op ); } \
  static inline sz_t bmath_f3_op_p_get_arity( const bmath_f3_op_s* __p, const bmath_f3_op* o ) { return __p->get_arity( o ); } \
  static inline sz_t bmath_f3_op_a_get_arity( const bmath_f3_op* o ) { return bmath_f3_op_s_get_aware( o )->get_arity( o ); } \
  static inline bl_t bmath_f3_op_p_defines_get_arity( const bmath_f3_op_s* __p ) { return __p->get_arity != NULL; } \
  static inline bl_t bmath_f3_op_a_defines_get_arity( const bmath_f3_op* o ) { return bmath_f3_op_s_get_aware( o )->get_arity != NULL; } \
  static inline f3_t bmath_f3_op_p_ofx( const bmath_f3_op_s* __p, const bmath_f3_op* o, const f3_t* a ) { return __p->ofx( o, a ); } \
  static inline f3_t bmath_f3_op_a_ofx( const bmath_f3_op* o, const f3_t* a ) { return bmath_f3_op_s_get_aware( o )->ofx( o, a ); } \
  static inline bl_t bmath_f3_op_p_defines_ofx( const bmath_f3_op_s* __p ) { return __p->ofx != NULL; } \
  static inline bl_t bmath_f3_op_a_defines_ofx( const bmath_f3_op* o ) { return bmath_f3_op_s_get_aware( o )->ofx != NULL; } \
  static inline f3_t bmath_f3_op_p_ogxi( const bmath_f3_op_s* __p, const bmath_f3_op* o, const f3_t* a, sz_t i ) { return __p->ogxi( o, a, i ); } \
  static inline f3_t bmath_f3_op_a_ogxi( const bmath_f3_op* o, const f3_t* a, sz_t i ) { return bmath_f3_op_s_get_aware( o )->ogxi( o, a, i ); } \
  static inline bl_t bmath_f3_op_p_defines_ogxi( const bmath_f3_op_s* __p ) { return __p->ogxi != NULL; } \
  static inline bl_t bmath_f3_op_a_defines_ogxi( const bmath_f3_op* o ) { return bmath_f3_op_s_get_aware( o )->ogxi != NULL; } \
  static inline f3_t bmath_f3_op_p_ogyi( const bmath_f3_op_s* __p, const bmath_f3_op* o, const f3_t* a, sz_t i ) { return __p->ogyi( o, a, i ); } \
  static inline f3_t bmath_f3_op_a_ogyi( const bmath_f3_op* o, const f3_t* a, sz_t i ) { return bmath_f3_op_s_get_aware( o )->ogyi( o, a, i ); } \
  static inline bl_t bmath_f3_op_p_defines_ogyi( const bmath_f3_op_s* __p ) { return __p->ogyi != NULL; } \
  static inline bl_t bmath_f3_op_a_defines_ogyi( const bmath_f3_op* o ) { return bmath_f3_op_s_get_aware( o )->ogyi != NULL; } \
  BETH_EXPAND_GROUP_bmath_f3_op_ar0 \
  BETH_EXPAND_GROUP_bmath_f3_op_ar1 \
  BETH_EXPAND_GROUP_bmath_f3_op_ar2

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op_ar0

#define TYPEOF_bmath_f3_op_ar0 513556885
#define TYPEOF_bmath_f3_op_ar0_s 335842807
#define TYPEOF_bmath_f3_op_ar0_zero_s 1600717790
#define BETH_EXPAND_ITEM_bmath_f3_op_ar0_zero_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar0_zero_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar0_zero_s_f( const bmath_f3_op_ar0_zero_s* o ){ return  0.0; } \
  static inline sz_t bmath_f3_op_ar0_zero_s_get_arity( const bmath_f3_op_ar0_zero_s* o ){ return 0; } \
  static inline f3_t bmath_f3_op_ar0_zero_s_ofx( const bmath_f3_op_ar0_zero_s* o, const f3_t* a ){ return bmath_f3_op_ar0_zero_s_f( o ); }
#define TYPEOF_bmath_f3_op_ar0_one_s 2829534504
#define BETH_EXPAND_ITEM_bmath_f3_op_ar0_one_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar0_one_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar0_one_s_f( const bmath_f3_op_ar0_one_s* o ){ return  1.0; } \
  static inline sz_t bmath_f3_op_ar0_one_s_get_arity( const bmath_f3_op_ar0_one_s* o ){ return 0; } \
  static inline f3_t bmath_f3_op_ar0_one_s_ofx( const bmath_f3_op_ar0_one_s* o, const f3_t* a ){ return bmath_f3_op_ar0_one_s_f( o ); }
#define TYPEOF_bmath_f3_op_ar0_literal_s 2842497783
#define BETH_EXPAND_ITEM_bmath_f3_op_ar0_literal_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar0_literal_s ) \
    {aware_t _;f3_t v;}; \
  static inline f3_t bmath_f3_op_ar0_literal_s_f( const bmath_f3_op_ar0_literal_s* o ){ return o->v; } \
  static inline sz_t bmath_f3_op_ar0_literal_s_get_arity( const bmath_f3_op_ar0_literal_s* o ){ return 0; } \
  static inline f3_t bmath_f3_op_ar0_literal_s_ofx( const bmath_f3_op_ar0_literal_s* o, const f3_t* a ){ return bmath_f3_op_ar0_literal_s_f( o ); }
#define BETH_EXPAND_GROUP_bmath_f3_op_ar0 \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar0_zero_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar0_one_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar0_literal_s ); \
  typedef f3_t (*bmath_f3_op_ar0_f)( const bmath_f3_op_ar0* o ); \
  BCORE_DECLARE_SPECT( bmath_f3_op_ar0 ) \
  { \
      bcore_spect_header_s header; \
      bmath_f3_op_ar0_f f; \
  }; \
  static inline bmath_f3_op_ar0* bmath_f3_op_ar0_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_f3_op_ar0, t ); return ( bmath_f3_op_ar0* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_f3_op_ar0_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_f3_op_ar0 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_f3_op_ar0 ) \
  static inline bl_t bmath_f3_op_ar0_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_f3_op_ar0 ); } \
  static inline f3_t bmath_f3_op_ar0_a_f( const bmath_f3_op_ar0* o ) { return bmath_f3_op_ar0_s_get_aware( o )->f( o ); } \
  static inline bl_t bmath_f3_op_ar0_a_defines_f( const bmath_f3_op_ar0* o ) { return bmath_f3_op_ar0_s_get_aware( o )->f != NULL; } \
  BETH_EXPAND_ITEM_bmath_f3_op_ar0_zero_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar0_one_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar0_literal_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op_ar1

#define TYPEOF_bmath_f3_op_ar1 496779266
#define TYPEOF_bmath_f3_op_ar1_s 2541499772
#define TYPEOF_bmath_f3_op_ar1_zero_s 1454831971
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_zero_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_zero_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_zero_s_fx( const bmath_f3_op_ar1_zero_s* o, f3_t a ){ return       0.0; } \
  static inline f3_t bmath_f3_op_ar1_zero_s_gy( const bmath_f3_op_ar1_zero_s* o, f3_t y ){ return  0.0; } \
  static inline sz_t bmath_f3_op_ar1_zero_s_get_arity( const bmath_f3_op_ar1_zero_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_zero_s_ofx( const bmath_f3_op_ar1_zero_s* o, const f3_t* a ){ return bmath_f3_op_ar1_zero_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_zero_s_ogyi( const bmath_f3_op_ar1_zero_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_zero_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_one_s 2623621383
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_one_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_one_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_one_s_fx( const bmath_f3_op_ar1_one_s* o, f3_t a ){ return       1.0; } \
  static inline f3_t bmath_f3_op_ar1_one_s_gy( const bmath_f3_op_ar1_one_s* o, f3_t y ){ return  0.0; } \
  static inline sz_t bmath_f3_op_ar1_one_s_get_arity( const bmath_f3_op_ar1_one_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_one_s_ofx( const bmath_f3_op_ar1_one_s* o, const f3_t* a ){ return bmath_f3_op_ar1_one_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_one_s_ogyi( const bmath_f3_op_ar1_one_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_one_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_identity_s 1923605299
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_identity_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_identity_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_identity_s_fx( const bmath_f3_op_ar1_identity_s* o, f3_t a ){ return        a ; } \
  static inline f3_t bmath_f3_op_ar1_identity_s_gy( const bmath_f3_op_ar1_identity_s* o, f3_t y ){ return  1.0; } \
  static inline sz_t bmath_f3_op_ar1_identity_s_get_arity( const bmath_f3_op_ar1_identity_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_identity_s_ofx( const bmath_f3_op_ar1_identity_s* o, const f3_t* a ){ return bmath_f3_op_ar1_identity_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_identity_s_ogyi( const bmath_f3_op_ar1_identity_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_identity_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_exp_s 3725340992
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_exp_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_exp_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_exp_s_fx( const bmath_f3_op_ar1_exp_s* o, f3_t a ){ return    exp(a); } \
  static inline f3_t bmath_f3_op_ar1_exp_s_gy( const bmath_f3_op_ar1_exp_s* o, f3_t y ){ return    y; } \
  static inline sz_t bmath_f3_op_ar1_exp_s_get_arity( const bmath_f3_op_ar1_exp_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_exp_s_ofx( const bmath_f3_op_ar1_exp_s* o, const f3_t* a ){ return bmath_f3_op_ar1_exp_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_exp_s_ogyi( const bmath_f3_op_ar1_exp_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_exp_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_inv_s 299842672
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_inv_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_inv_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_inv_s_fx( const bmath_f3_op_ar1_inv_s* o, f3_t a ){ return f3_inv(a); } \
  static inline f3_t bmath_f3_op_ar1_inv_s_gy( const bmath_f3_op_ar1_inv_s* o, f3_t y ){ return -y*y; } \
  static inline sz_t bmath_f3_op_ar1_inv_s_get_arity( const bmath_f3_op_ar1_inv_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_inv_s_ofx( const bmath_f3_op_ar1_inv_s* o, const f3_t* a ){ return bmath_f3_op_ar1_inv_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_inv_s_ogyi( const bmath_f3_op_ar1_inv_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_inv_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_lgst_s 333512919
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_lgst_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_lgst_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_lgst_s_fx( const bmath_f3_op_ar1_lgst_s* o, f3_t a ){ return ( a > -700 ) ? ( 1.0 / ( 1.0 + exp( -a ) ) ) : 0; } \
  static inline f3_t bmath_f3_op_ar1_lgst_s_gy( const bmath_f3_op_ar1_lgst_s* o, f3_t y ){ return y * ( 1.0 - y ); } \
  static inline sz_t bmath_f3_op_ar1_lgst_s_get_arity( const bmath_f3_op_ar1_lgst_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_lgst_s_ofx( const bmath_f3_op_ar1_lgst_s* o, const f3_t* a ){ return bmath_f3_op_ar1_lgst_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_lgst_s_ogyi( const bmath_f3_op_ar1_lgst_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_lgst_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_lgst_hard_s 2938768633
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_lgst_hard_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_lgst_hard_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_lgst_hard_s_fx( const bmath_f3_op_ar1_lgst_hard_s* o, f3_t a ){ return ( a < -2.0 ) ? 0.0 : ( a > 2.0 ) ? 1.0 : 0.25 * ( a + 2.0 ); } \
  static inline f3_t bmath_f3_op_ar1_lgst_hard_s_gy( const bmath_f3_op_ar1_lgst_hard_s* o, f3_t y ){ return ( y <  0.0 ) ? 0.0 : ( y > 1.0 ) ? 0.0 : 0.25; } \
  static inline sz_t bmath_f3_op_ar1_lgst_hard_s_get_arity( const bmath_f3_op_ar1_lgst_hard_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_lgst_hard_s_ofx( const bmath_f3_op_ar1_lgst_hard_s* o, const f3_t* a ){ return bmath_f3_op_ar1_lgst_hard_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_lgst_hard_s_ogyi( const bmath_f3_op_ar1_lgst_hard_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_lgst_hard_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_lgst_leaky_s 4083486954
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_lgst_leaky_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_lgst_leaky_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_lgst_leaky_s_fx( const bmath_f3_op_ar1_lgst_leaky_s* o, f3_t a ){ return ( a < -2.0 ) ? 0.01 * ( a + 2.0 ) : ( a > 2.0 ) ? 1.0 + 0.01 * ( a - 2.0 ) : 0.25 * ( a + 2.0 ); } \
  static inline f3_t bmath_f3_op_ar1_lgst_leaky_s_gy( const bmath_f3_op_ar1_lgst_leaky_s* o, f3_t y ){ return ( y <  0.0 ) ? 0.01 : ( y > 1.0 ) ? 0.01 : 0.25; } \
  static inline sz_t bmath_f3_op_ar1_lgst_leaky_s_get_arity( const bmath_f3_op_ar1_lgst_leaky_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_lgst_leaky_s_ofx( const bmath_f3_op_ar1_lgst_leaky_s* o, const f3_t* a ){ return bmath_f3_op_ar1_lgst_leaky_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_lgst_leaky_s_ogyi( const bmath_f3_op_ar1_lgst_leaky_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_lgst_leaky_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_tanh_s 1788001760
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_tanh_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_tanh_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_tanh_s_fx( const bmath_f3_op_ar1_tanh_s* o, f3_t a ){ return ( a < 350 ) ? ( 1.0 - ( 2.0 / ( exp( 2.0 * a ) + 1.0 ) ) ) : 1.0; } \
  static inline f3_t bmath_f3_op_ar1_tanh_s_gy( const bmath_f3_op_ar1_tanh_s* o, f3_t y ){ return 1.0 - f3_sqr( y ); } \
  static inline sz_t bmath_f3_op_ar1_tanh_s_get_arity( const bmath_f3_op_ar1_tanh_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_tanh_s_ofx( const bmath_f3_op_ar1_tanh_s* o, const f3_t* a ){ return bmath_f3_op_ar1_tanh_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_tanh_s_ogyi( const bmath_f3_op_ar1_tanh_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_tanh_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_tanh_hard_s 3038132616
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_tanh_hard_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_tanh_hard_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_tanh_hard_s_fx( const bmath_f3_op_ar1_tanh_hard_s* o, f3_t a ){ return ( a < -1.0 ) ? -1.0 : ( a > 1.0 ) ? 1.0 : a; } \
  static inline f3_t bmath_f3_op_ar1_tanh_hard_s_gy( const bmath_f3_op_ar1_tanh_hard_s* o, f3_t y ){ return ( y < -1.0 ) ?  0.0 : ( y > 1.0 ) ? 0.0 : 1.0; } \
  static inline sz_t bmath_f3_op_ar1_tanh_hard_s_get_arity( const bmath_f3_op_ar1_tanh_hard_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_tanh_hard_s_ofx( const bmath_f3_op_ar1_tanh_hard_s* o, const f3_t* a ){ return bmath_f3_op_ar1_tanh_hard_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_tanh_hard_s_ogyi( const bmath_f3_op_ar1_tanh_hard_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_tanh_hard_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_tanh_leaky_s 2633497533
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_tanh_leaky_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_tanh_leaky_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_tanh_leaky_s_fx( const bmath_f3_op_ar1_tanh_leaky_s* o, f3_t a ){ return ( a < -1.0 ) ? -1.0 + 0.01 * ( a + 1.0 ) : ( a > 1.0 ) ? 1.0 + 0.01 * ( a - 1.0 ) : a; } \
  static inline f3_t bmath_f3_op_ar1_tanh_leaky_s_gy( const bmath_f3_op_ar1_tanh_leaky_s* o, f3_t y ){ return ( y < -1.0 ) ?  0.01 : ( y > 1.0 ) ? 0.01 : 1.0; } \
  static inline sz_t bmath_f3_op_ar1_tanh_leaky_s_get_arity( const bmath_f3_op_ar1_tanh_leaky_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_tanh_leaky_s_ofx( const bmath_f3_op_ar1_tanh_leaky_s* o, const f3_t* a ){ return bmath_f3_op_ar1_tanh_leaky_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_tanh_leaky_s_ogyi( const bmath_f3_op_ar1_tanh_leaky_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_tanh_leaky_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_softplus_s 3026965625
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_softplus_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_softplus_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_softplus_s_fx( const bmath_f3_op_ar1_softplus_s* o, f3_t a ){ return ( a < 700 ) ? log( 1.0 + exp( a ) ) : a; } \
  static inline f3_t bmath_f3_op_ar1_softplus_s_gy( const bmath_f3_op_ar1_softplus_s* o, f3_t y ){ f3_t u = exp( y ); return ( u - 1.0 ) / u; } \
  static inline sz_t bmath_f3_op_ar1_softplus_s_get_arity( const bmath_f3_op_ar1_softplus_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_softplus_s_ofx( const bmath_f3_op_ar1_softplus_s* o, const f3_t* a ){ return bmath_f3_op_ar1_softplus_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_softplus_s_ogyi( const bmath_f3_op_ar1_softplus_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_softplus_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_relu_s 2725306995
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_relu_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_relu_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_relu_s_fx( const bmath_f3_op_ar1_relu_s* o, f3_t a ){ return a > 0 ? a : 0; } \
  static inline f3_t bmath_f3_op_ar1_relu_s_gy( const bmath_f3_op_ar1_relu_s* o, f3_t y ){ return y > 0 ? 1 : 0; } \
  static inline sz_t bmath_f3_op_ar1_relu_s_get_arity( const bmath_f3_op_ar1_relu_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_relu_s_ofx( const bmath_f3_op_ar1_relu_s* o, const f3_t* a ){ return bmath_f3_op_ar1_relu_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_relu_s_ogyi( const bmath_f3_op_ar1_relu_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_relu_s_gy( o, a[0] ); }
#define TYPEOF_bmath_f3_op_ar1_relu_leaky_s 1382667214
#define BETH_EXPAND_ITEM_bmath_f3_op_ar1_relu_leaky_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar1_relu_leaky_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar1_relu_leaky_s_fx( const bmath_f3_op_ar1_relu_leaky_s* o, f3_t a ){ return a > 0 ? a : a * 0.01; } \
  static inline f3_t bmath_f3_op_ar1_relu_leaky_s_gy( const bmath_f3_op_ar1_relu_leaky_s* o, f3_t y ){ return y > 0 ? 1 : 0.01; } \
  static inline sz_t bmath_f3_op_ar1_relu_leaky_s_get_arity( const bmath_f3_op_ar1_relu_leaky_s* o ){ return 1; } \
  static inline f3_t bmath_f3_op_ar1_relu_leaky_s_ofx( const bmath_f3_op_ar1_relu_leaky_s* o, const f3_t* a ){ return bmath_f3_op_ar1_relu_leaky_s_fx( o, a[0] ); } \
  static inline f3_t bmath_f3_op_ar1_relu_leaky_s_ogyi( const bmath_f3_op_ar1_relu_leaky_s* o, const f3_t* a, sz_t i ){ return bmath_f3_op_ar1_relu_leaky_s_gy( o, a[0] ); }
#define BETH_EXPAND_GROUP_bmath_f3_op_ar1 \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_zero_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_one_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_identity_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_exp_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_inv_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_lgst_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_lgst_hard_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_lgst_leaky_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_tanh_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_tanh_hard_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_tanh_leaky_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_softplus_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_relu_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar1_relu_leaky_s ); \
  typedef f3_t (*bmath_f3_op_ar1_fx)( const bmath_f3_op_ar1* o, f3_t a ); \
  typedef f3_t (*bmath_f3_op_ar1_gy)( const bmath_f3_op_ar1* o, f3_t y ); \
  BCORE_DECLARE_SPECT( bmath_f3_op_ar1 ) \
  { \
      bcore_spect_header_s header; \
      bmath_f3_op_ar1_fx fx; \
      bmath_f3_op_ar1_gy gy; \
  }; \
  static inline bmath_f3_op_ar1* bmath_f3_op_ar1_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_f3_op_ar1, t ); return ( bmath_f3_op_ar1* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_f3_op_ar1_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_f3_op_ar1 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_f3_op_ar1 ) \
  static inline bl_t bmath_f3_op_ar1_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_f3_op_ar1 ); } \
  static inline f3_t bmath_f3_op_ar1_a_fx( const bmath_f3_op_ar1* o, f3_t a ) { return bmath_f3_op_ar1_s_get_aware( o )->fx( o, a ); } \
  static inline bl_t bmath_f3_op_ar1_a_defines_fx( const bmath_f3_op_ar1* o ) { return bmath_f3_op_ar1_s_get_aware( o )->fx != NULL; } \
  static inline f3_t bmath_f3_op_ar1_a_gy( const bmath_f3_op_ar1* o, f3_t y ) { return bmath_f3_op_ar1_s_get_aware( o )->gy( o, y ); } \
  static inline bl_t bmath_f3_op_ar1_a_defines_gy( const bmath_f3_op_ar1* o ) { return bmath_f3_op_ar1_s_get_aware( o )->gy != NULL; } \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_zero_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_one_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_identity_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_exp_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_inv_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_lgst_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_lgst_hard_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_lgst_leaky_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_tanh_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_tanh_hard_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_tanh_leaky_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_softplus_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_relu_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar1_relu_leaky_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_f3_op_ar2

#define TYPEOF_bmath_f3_op_ar2 480001647
#define TYPEOF_bmath_f3_op_ar2_s 555279449
#define TYPEOF_bmath_f3_op_ar2_add_s 4091197653
#define BETH_EXPAND_ITEM_bmath_f3_op_ar2_add_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar2_add_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar2_add_s_fx( const bmath_f3_op_ar2_add_s* o, f3_t a, f3_t b ){ return a + b; } \
  static inline f3_t bmath_f3_op_ar2_add_s_gxa( const bmath_f3_op_ar2_add_s* o, f3_t a, f3_t b ){ return 1; } \
  static inline f3_t bmath_f3_op_ar2_add_s_gxb( const bmath_f3_op_ar2_add_s* o, f3_t a, f3_t b ){ return 1; } \
  static inline sz_t bmath_f3_op_ar2_add_s_get_arity( const bmath_f3_op_ar2_add_s* o ){ return 2; } \
  static inline f3_t bmath_f3_op_ar2_add_s_ofx( const bmath_f3_op_ar2_add_s* o, const f3_t* a ){ return bmath_f3_op_ar2_add_s_fx( o, a[0], a[1] ); } \
  static inline f3_t bmath_f3_op_ar2_add_s_ogxi( const bmath_f3_op_ar2_add_s* o, const f3_t* a, sz_t i ){ return ( i == 0 ) ? bmath_f3_op_ar2_add_s_gxa( o, a[0], a[1] ) : bmath_f3_op_ar2_add_s_gxb( o, a[0], a[1] ); }
#define TYPEOF_bmath_f3_op_ar2_sub_s 967394508
#define BETH_EXPAND_ITEM_bmath_f3_op_ar2_sub_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar2_sub_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar2_sub_s_fx( const bmath_f3_op_ar2_sub_s* o, f3_t a, f3_t b ){ return a - b; } \
  static inline f3_t bmath_f3_op_ar2_sub_s_gxa( const bmath_f3_op_ar2_sub_s* o, f3_t a, f3_t b ){ return  1; } \
  static inline f3_t bmath_f3_op_ar2_sub_s_gxb( const bmath_f3_op_ar2_sub_s* o, f3_t a, f3_t b ){ return -1; } \
  static inline sz_t bmath_f3_op_ar2_sub_s_get_arity( const bmath_f3_op_ar2_sub_s* o ){ return 2; } \
  static inline f3_t bmath_f3_op_ar2_sub_s_ofx( const bmath_f3_op_ar2_sub_s* o, const f3_t* a ){ return bmath_f3_op_ar2_sub_s_fx( o, a[0], a[1] ); } \
  static inline f3_t bmath_f3_op_ar2_sub_s_ogxi( const bmath_f3_op_ar2_sub_s* o, const f3_t* a, sz_t i ){ return ( i == 0 ) ? bmath_f3_op_ar2_sub_s_gxa( o, a[0], a[1] ) : bmath_f3_op_ar2_sub_s_gxb( o, a[0], a[1] ); }
#define TYPEOF_bmath_f3_op_ar2_mul_s 1939336112
#define BETH_EXPAND_ITEM_bmath_f3_op_ar2_mul_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar2_mul_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar2_mul_s_fx( const bmath_f3_op_ar2_mul_s* o, f3_t a, f3_t b ){ return a * b; } \
  static inline f3_t bmath_f3_op_ar2_mul_s_gxa( const bmath_f3_op_ar2_mul_s* o, f3_t a, f3_t b ){ return b; } \
  static inline f3_t bmath_f3_op_ar2_mul_s_gxb( const bmath_f3_op_ar2_mul_s* o, f3_t a, f3_t b ){ return a; } \
  static inline sz_t bmath_f3_op_ar2_mul_s_get_arity( const bmath_f3_op_ar2_mul_s* o ){ return 2; } \
  static inline f3_t bmath_f3_op_ar2_mul_s_ofx( const bmath_f3_op_ar2_mul_s* o, const f3_t* a ){ return bmath_f3_op_ar2_mul_s_fx( o, a[0], a[1] ); } \
  static inline f3_t bmath_f3_op_ar2_mul_s_ogxi( const bmath_f3_op_ar2_mul_s* o, const f3_t* a, sz_t i ){ return ( i == 0 ) ? bmath_f3_op_ar2_mul_s_gxa( o, a[0], a[1] ) : bmath_f3_op_ar2_mul_s_gxb( o, a[0], a[1] ); }
#define TYPEOF_bmath_f3_op_ar2_div_s 3454172141
#define BETH_EXPAND_ITEM_bmath_f3_op_ar2_div_s \
  BCORE_DECLARE_OBJECT( bmath_f3_op_ar2_div_s ) \
    {aware_t _;}; \
  static inline f3_t bmath_f3_op_ar2_div_s_fx( const bmath_f3_op_ar2_div_s* o, f3_t a, f3_t b ){ return b != 0 ?   a / b         :  a * f3_lim_inf; } \
  static inline f3_t bmath_f3_op_ar2_div_s_gxa( const bmath_f3_op_ar2_div_s* o, f3_t a, f3_t b ){ return b != 0 ? 1.0 / b         :      f3_lim_inf; } \
  static inline f3_t bmath_f3_op_ar2_div_s_gxb( const bmath_f3_op_ar2_div_s* o, f3_t a, f3_t b ){ return b != 0 ?  -a / ( b * b ) : -a * f3_lim_inf; } \
  static inline sz_t bmath_f3_op_ar2_div_s_get_arity( const bmath_f3_op_ar2_div_s* o ){ return 2; } \
  static inline f3_t bmath_f3_op_ar2_div_s_ofx( const bmath_f3_op_ar2_div_s* o, const f3_t* a ){ return bmath_f3_op_ar2_div_s_fx( o, a[0], a[1] ); } \
  static inline f3_t bmath_f3_op_ar2_div_s_ogxi( const bmath_f3_op_ar2_div_s* o, const f3_t* a, sz_t i ){ return ( i == 0 ) ? bmath_f3_op_ar2_div_s_gxa( o, a[0], a[1] ) : bmath_f3_op_ar2_div_s_gxb( o, a[0], a[1] ); }
#define BETH_EXPAND_GROUP_bmath_f3_op_ar2 \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar2 ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar2_add_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar2_sub_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar2_mul_s ); \
  BCORE_FORWARD_OBJECT( bmath_f3_op_ar2_div_s ); \
  typedef f3_t (*bmath_f3_op_ar2_fx)( const bmath_f3_op_ar2* o, f3_t a, f3_t b ); \
  typedef f3_t (*bmath_f3_op_ar2_gxa)( const bmath_f3_op_ar2* o, f3_t a, f3_t b ); \
  typedef f3_t (*bmath_f3_op_ar2_gxb)( const bmath_f3_op_ar2* o, f3_t a, f3_t b ); \
  BCORE_DECLARE_SPECT( bmath_f3_op_ar2 ) \
  { \
      bcore_spect_header_s header; \
      bmath_f3_op_ar2_fx fx; \
      bmath_f3_op_ar2_gxa gxa; \
      bmath_f3_op_ar2_gxb gxb; \
  }; \
  static inline bmath_f3_op_ar2* bmath_f3_op_ar2_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_f3_op_ar2, t ); return ( bmath_f3_op_ar2* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_f3_op_ar2_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_f3_op_ar2 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_f3_op_ar2 ) \
  static inline bl_t bmath_f3_op_ar2_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_f3_op_ar2 ); } \
  static inline f3_t bmath_f3_op_ar2_a_fx( const bmath_f3_op_ar2* o, f3_t a, f3_t b ) { return bmath_f3_op_ar2_s_get_aware( o )->fx( o, a, b ); } \
  static inline bl_t bmath_f3_op_ar2_a_defines_fx( const bmath_f3_op_ar2* o ) { return bmath_f3_op_ar2_s_get_aware( o )->fx != NULL; } \
  static inline f3_t bmath_f3_op_ar2_a_gxa( const bmath_f3_op_ar2* o, f3_t a, f3_t b ) { return bmath_f3_op_ar2_s_get_aware( o )->gxa( o, a, b ); } \
  static inline bl_t bmath_f3_op_ar2_a_defines_gxa( const bmath_f3_op_ar2* o ) { return bmath_f3_op_ar2_s_get_aware( o )->gxa != NULL; } \
  static inline f3_t bmath_f3_op_ar2_a_gxb( const bmath_f3_op_ar2* o, f3_t a, f3_t b ) { return bmath_f3_op_ar2_s_get_aware( o )->gxb( o, a, b ); } \
  static inline bl_t bmath_f3_op_ar2_a_defines_gxb( const bmath_f3_op_ar2* o ) { return bmath_f3_op_ar2_s_get_aware( o )->gxb != NULL; } \
  BETH_EXPAND_ITEM_bmath_f3_op_ar2_add_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar2_sub_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar2_mul_s \
  BETH_EXPAND_ITEM_bmath_f3_op_ar2_div_s

/**********************************************************************************************************************/
// source: bmath_mf3_sx.h

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_mf3_sx

#define TYPEOF_bmath_mf3_sx 934545414
#define TYPEOF_bmath_mf3_sx_s 948195256
#define TYPEOF_bmath_mf3_sx_s 948195256
#define BETH_EXPAND_ITEM_bmath_mf3_sx_s \
  BCORE_DECLARE_OBJECT( bmath_mf3_sx_s ) \
    {aware_t _;sz_t slos;sz_t xons;sz_t rows;sz_t i_stride;BCORE_ARRAY_DYN_SOLID_STATIC_S( sz_t, i_ );BCORE_ARRAY_DYN_SOLID_STATIC_S( f3_t, v_ );};
#define BETH_EXPAND_GROUP_bmath_mf3_sx \
  BCORE_FORWARD_OBJECT( bmath_mf3_sx ); \
  BCORE_FORWARD_OBJECT( bmath_mf3_sx_s ); \
  BETH_EXPAND_ITEM_bmath_mf3_sx_s

/**********************************************************************************************************************/
// source: bmath_mf3_sf.h

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_mf3_sf

#define TYPEOF_bmath_mf3_sf 1370763508
#define TYPEOF_bmath_mf3_sf_s 913280742
#define TYPEOF_bmath_mf3_sf_s 913280742
#define BETH_EXPAND_ITEM_bmath_mf3_sf_s \
  BCORE_DECLARE_OBJECT( bmath_mf3_sf_s ) \
    {aware_t _;sz_t cols;sz_t rows;sz_t i_stride;BCORE_ARRAY_DYN_SOLID_STATIC_S( sz_t, i_ );BCORE_ARRAY_DYN_SOLID_STATIC_S( f3_t, v_ );};
#define BETH_EXPAND_GROUP_bmath_mf3_sf \
  BCORE_FORWARD_OBJECT( bmath_mf3_sf ); \
  BCORE_FORWARD_OBJECT( bmath_mf3_sf_s ); \
  BETH_EXPAND_ITEM_bmath_mf3_sf_s

/**********************************************************************************************************************/
// source: bmath_hf3.h

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3

#define TYPEOF_bmath_hf3 3901573499
#define TYPEOF_bmath_hf3_s 3558242317
#define TYPEOF_bmath_hf3_s 3558242317
#define BETH_EXPAND_ITEM_bmath_hf3_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_s ) \
    {aware_t _;BCORE_ARRAY_DYN_SOLID_STATIC_S( sz_t, d_ );BCORE_ARRAY_DYN_SOLID_STATIC_S( f3_t, v_ );};
#define TYPEOF_bmath_hf3_adl_s 3605419337
#define BETH_EXPAND_ITEM_bmath_hf3_adl_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_adl_s ) \
    {aware_t _;BCORE_ARRAY_DYN_LINK_STATIC_S( bmath_hf3_s, );}; \
  static inline void bmath_hf3_adl_s_set_space( bmath_hf3_adl_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_adl_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_adl_s_set_size( bmath_hf3_adl_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bmath_hf3_adl_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_adl_s_clear( bmath_hf3_adl_s* o ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_adl_s, ( bcore_array* )o, 0 ); } \
  static inline bmath_hf3_s* bmath_hf3_adl_s_push_c( bmath_hf3_adl_s* o, const bmath_hf3_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_adl_s, ( bcore_array* )o, sr_twc( TYPEOF_bmath_hf3_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_s* bmath_hf3_adl_s_push_d( bmath_hf3_adl_s* o,       bmath_hf3_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_adl_s, ( bcore_array* )o, sr_tsd( TYPEOF_bmath_hf3_s, v ) ); return o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_s* bmath_hf3_adl_s_push( bmath_hf3_adl_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bmath_hf3_adl_s, ( bcore_array* )o, sr_t_create( TYPEOF_bmath_hf3_s ) ); \
      return o->data[ o->size - 1 ]; \
  }
#define BETH_EXPAND_GROUP_bmath_hf3 \
  BCORE_FORWARD_OBJECT( bmath_hf3 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_adl_s ); \
  BETH_EXPAND_ITEM_bmath_hf3_s \
  BETH_EXPAND_ITEM_bmath_hf3_adl_s

/**********************************************************************************************************************/
// source: bmath_hf3_op.h

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_op

#define TYPEOF_bmath_hf3_op 1410918571
#define TYPEOF_bmath_hf3_op_s 3122943677
#define BETH_EXPAND_GROUP_bmath_hf3_op \
  BCORE_FORWARD_OBJECT( bmath_hf3_op ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar2 ); \
  typedef sz_t (*bmath_hf3_op_get_arity)( const bmath_hf3_op* o ); \
  typedef void (*bmath_hf3_op_ofx)( const bmath_hf3_op* o, const bmath_hf3_s** a, bmath_hf3_s* r ); \
  typedef void (*bmath_hf3_op_ogx)( const bmath_hf3_op* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ); \
  typedef void (*bmath_hf3_op_ogy)( const bmath_hf3_op* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bmath_hf3_op ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_op_get_arity get_arity; \
      bmath_hf3_op_ofx ofx; \
      bmath_hf3_op_ogx ogx; \
      bmath_hf3_op_ogy ogy; \
  }; \
  static inline bmath_hf3_op* bmath_hf3_op_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_op, t ); return ( bmath_hf3_op* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_op_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_op ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_op ) \
  static inline bl_t bmath_hf3_op_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_op ); } \
  static inline sz_t bmath_hf3_op_p_get_arity( const bmath_hf3_op_s* __p, const bmath_hf3_op* o ) { return __p->get_arity( o ); } \
  static inline sz_t bmath_hf3_op_a_get_arity( const bmath_hf3_op* o ) { return bmath_hf3_op_s_get_aware( o )->get_arity( o ); } \
  static inline bl_t bmath_hf3_op_p_defines_get_arity( const bmath_hf3_op_s* __p ) { return __p->get_arity != NULL; } \
  static inline bl_t bmath_hf3_op_a_defines_get_arity( const bmath_hf3_op* o ) { return bmath_hf3_op_s_get_aware( o )->get_arity != NULL; } \
  static inline void bmath_hf3_op_p_ofx( const bmath_hf3_op_s* __p, const bmath_hf3_op* o, const bmath_hf3_s** a, bmath_hf3_s* r ) { __p->ofx( o, a, r ); } \
  static inline void bmath_hf3_op_a_ofx( const bmath_hf3_op* o, const bmath_hf3_s** a, bmath_hf3_s* r ) { bmath_hf3_op_s_get_aware( o )->ofx( o, a, r ); } \
  static inline bl_t bmath_hf3_op_p_defines_ofx( const bmath_hf3_op_s* __p ) { return __p->ofx != NULL; } \
  static inline bl_t bmath_hf3_op_a_defines_ofx( const bmath_hf3_op* o ) { return bmath_hf3_op_s_get_aware( o )->ofx != NULL; } \
  static inline void bmath_hf3_op_p_ogx( const bmath_hf3_op_s* __p, const bmath_hf3_op* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ) { __p->ogx( o, i, a, r ); } \
  static inline void bmath_hf3_op_a_ogx( const bmath_hf3_op* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ) { bmath_hf3_op_s_get_aware( o )->ogx( o, i, a, r ); } \
  static inline bl_t bmath_hf3_op_p_defines_ogx( const bmath_hf3_op_s* __p ) { return __p->ogx != NULL; } \
  static inline bl_t bmath_hf3_op_a_defines_ogx( const bmath_hf3_op* o ) { return bmath_hf3_op_s_get_aware( o )->ogx != NULL; } \
  static inline void bmath_hf3_op_p_ogy( const bmath_hf3_op_s* __p, const bmath_hf3_op* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ) { __p->ogy( o, i, a, r ); } \
  static inline void bmath_hf3_op_a_ogy( const bmath_hf3_op* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ) { bmath_hf3_op_s_get_aware( o )->ogy( o, i, a, r ); } \
  static inline bl_t bmath_hf3_op_p_defines_ogy( const bmath_hf3_op_s* __p ) { return __p->ogy != NULL; } \
  static inline bl_t bmath_hf3_op_a_defines_ogy( const bmath_hf3_op* o ) { return bmath_hf3_op_s_get_aware( o )->ogy != NULL; } \
  BETH_EXPAND_GROUP_bmath_hf3_op_ar0 \
  BETH_EXPAND_GROUP_bmath_hf3_op_ar1 \
  BETH_EXPAND_GROUP_bmath_hf3_op_ar2

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_op_ar0

#define TYPEOF_bmath_hf3_op_ar0 438877965
#define TYPEOF_bmath_hf3_op_ar0_s 529008895
#define TYPEOF_bmath_hf3_op_ar0_zero_s 3734107878
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar0_zero_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar0_zero_s ) \
    {aware_t _;}; \
  static inline void bmath_hf3_op_ar0_zero_s_f( const bmath_hf3_op_ar0_zero_s* o, bmath_hf3_s* r ){ bmath_hf3_s_zro( r ); } \
  static inline sz_t bmath_hf3_op_ar0_zero_s_get_arity( const bmath_hf3_op_ar0_zero_s* o ){ return 0; } \
  static inline void bmath_hf3_op_ar0_zero_s_ofx( const bmath_hf3_op_ar0_zero_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar0_zero_s_f( o, r ); }
#define TYPEOF_bmath_hf3_op_ar0_literal_s 495704543
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar0_literal_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar0_literal_s ) \
    {aware_t _;bmath_hf3_s* h;}; \
  static inline void bmath_hf3_op_ar0_literal_s_f( const bmath_hf3_op_ar0_literal_s* o, bmath_hf3_s* r ){ bmath_hf3_s_cpy( o->h, r ); } \
  static inline sz_t bmath_hf3_op_ar0_literal_s_get_arity( const bmath_hf3_op_ar0_literal_s* o ){ return 0; } \
  static inline void bmath_hf3_op_ar0_literal_s_ofx( const bmath_hf3_op_ar0_literal_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar0_literal_s_f( o, r ); }
#define TYPEOF_bmath_hf3_op_ar0_f3_s 2339803667
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar0_f3_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar0_f3_s ) \
    {aware_t _;bmath_f3_op_ar0* op;}; \
  static inline void bmath_hf3_op_ar0_f3_s_f( const bmath_hf3_op_ar0_f3_s* o, bmath_hf3_s* r ){ bmath_hf3_s_fp_f3_op_ar0( r, ( bmath_fp_f3_op_ar0 )bmath_f3_op_ar0_s_get_aware( o->op )->f, o->op ); } \
  static inline sz_t bmath_hf3_op_ar0_f3_s_get_arity( const bmath_hf3_op_ar0_f3_s* o ){ return 0; } \
  static inline void bmath_hf3_op_ar0_f3_s_ofx( const bmath_hf3_op_ar0_f3_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar0_f3_s_f( o, r ); }
#define BETH_EXPAND_GROUP_bmath_hf3_op_ar0 \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar0_zero_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar0_literal_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar0_f3_s ); \
  typedef void (*bmath_hf3_op_ar0_f)( const bmath_hf3_op_ar0* o, bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bmath_hf3_op_ar0 ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_op_ar0_f f; \
  }; \
  static inline bmath_hf3_op_ar0* bmath_hf3_op_ar0_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_op_ar0, t ); return ( bmath_hf3_op_ar0* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_op_ar0_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_op_ar0 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_op_ar0 ) \
  static inline bl_t bmath_hf3_op_ar0_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_op_ar0 ); } \
  static inline void bmath_hf3_op_ar0_a_f( const bmath_hf3_op_ar0* o, bmath_hf3_s* r ) { bmath_hf3_op_ar0_s_get_aware( o )->f( o, r ); } \
  static inline bl_t bmath_hf3_op_ar0_a_defines_f( const bmath_hf3_op_ar0* o ) { return bmath_hf3_op_ar0_s_get_aware( o )->f != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar0_zero_s \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar0_literal_s \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar0_f3_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_op_ar1

#define TYPEOF_bmath_hf3_op_ar1 422100346
#define TYPEOF_bmath_hf3_op_ar1_s 3240315556
#define TYPEOF_bmath_hf3_op_ar1_identity_s 2366359675
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar1_identity_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar1_identity_s ) \
    {aware_t _;}; \
  static inline void bmath_hf3_op_ar1_identity_s_fx( const bmath_hf3_op_ar1_identity_s* o, const bmath_hf3_s* a, bmath_hf3_s* r ){ bmath_hf3_s_cpy( a, r ); } \
  static inline void bmath_hf3_op_ar1_identity_s_gy( const bmath_hf3_op_ar1_identity_s* o, const bmath_hf3_s* y, bmath_hf3_s* r ){ bmath_hf3_s_set_f3( r, 1.0 ); } \
  static inline sz_t bmath_hf3_op_ar1_identity_s_get_arity( const bmath_hf3_op_ar1_identity_s* o ){ return 1; } \
  static inline void bmath_hf3_op_ar1_identity_s_ofx( const bmath_hf3_op_ar1_identity_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar1_identity_s_fx( o, a[0], r ); } \
  static inline void bmath_hf3_op_ar1_identity_s_ogy( const bmath_hf3_op_ar1_identity_s* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar1_identity_s_gy( o, a[0], r ); }
#define TYPEOF_bmath_hf3_op_ar1_f3_s 4161577250
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar1_f3_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar1_f3_s ) \
    {aware_t _;bmath_f3_op_ar1* op;}; \
  static inline void bmath_hf3_op_ar1_f3_s_fx( const bmath_hf3_op_ar1_f3_s* o, const bmath_hf3_s* a, bmath_hf3_s* r ){ bmath_hf3_s_fp_f3_op_ar1( a, ( bmath_fp_f3_op_ar1 )bmath_f3_op_ar1_s_get_aware( o->op )->fx, o->op, r ); } \
  static inline void bmath_hf3_op_ar1_f3_s_gy( const bmath_hf3_op_ar1_f3_s* o, const bmath_hf3_s* y, bmath_hf3_s* r ){ bmath_hf3_s_fp_f3_op_ar1( y, ( bmath_fp_f3_op_ar1 )bmath_f3_op_ar1_s_get_aware( o->op )->gy, o->op, r ); } \
  static inline sz_t bmath_hf3_op_ar1_f3_s_get_arity( const bmath_hf3_op_ar1_f3_s* o ){ return 1; } \
  static inline void bmath_hf3_op_ar1_f3_s_ofx( const bmath_hf3_op_ar1_f3_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar1_f3_s_fx( o, a[0], r ); } \
  static inline void bmath_hf3_op_ar1_f3_s_ogy( const bmath_hf3_op_ar1_f3_s* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar1_f3_s_gy( o, a[0], r ); }
#define BETH_EXPAND_GROUP_bmath_hf3_op_ar1 \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar1_identity_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar1_f3_s ); \
  typedef void (*bmath_hf3_op_ar1_fx)( const bmath_hf3_op_ar1* o, const bmath_hf3_s* a, bmath_hf3_s* r ); \
  typedef void (*bmath_hf3_op_ar1_gy)( const bmath_hf3_op_ar1* o, const bmath_hf3_s* y, bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bmath_hf3_op_ar1 ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_op_ar1_fx fx; \
      bmath_hf3_op_ar1_gy gy; \
  }; \
  static inline bmath_hf3_op_ar1* bmath_hf3_op_ar1_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_op_ar1, t ); return ( bmath_hf3_op_ar1* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_op_ar1_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_op_ar1 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_op_ar1 ) \
  static inline bl_t bmath_hf3_op_ar1_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_op_ar1 ); } \
  static inline void bmath_hf3_op_ar1_a_fx( const bmath_hf3_op_ar1* o, const bmath_hf3_s* a, bmath_hf3_s* r ) { bmath_hf3_op_ar1_s_get_aware( o )->fx( o, a, r ); } \
  static inline bl_t bmath_hf3_op_ar1_a_defines_fx( const bmath_hf3_op_ar1* o ) { return bmath_hf3_op_ar1_s_get_aware( o )->fx != NULL; } \
  static inline void bmath_hf3_op_ar1_a_gy( const bmath_hf3_op_ar1* o, const bmath_hf3_s* y, bmath_hf3_s* r ) { bmath_hf3_op_ar1_s_get_aware( o )->gy( o, y, r ); } \
  static inline bl_t bmath_hf3_op_ar1_a_defines_gy( const bmath_hf3_op_ar1* o ) { return bmath_hf3_op_ar1_s_get_aware( o )->gy != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar1_identity_s \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar1_f3_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_op_ar2

#define TYPEOF_bmath_hf3_op_ar2 405322727
#define TYPEOF_bmath_hf3_op_ar2_s 1285226177
#define TYPEOF_bmath_hf3_op_ar2_add_s 1871698317
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar2_add_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar2_add_s ) \
    {aware_t _;}; \
  static inline void bmath_hf3_op_ar2_add_s_fx( const bmath_hf3_op_ar2_add_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_add( a, b, r ); } \
  static inline void bmath_hf3_op_ar2_add_s_gxa( const bmath_hf3_op_ar2_add_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_set_f3( r, 1.0 ); } \
  static inline void bmath_hf3_op_ar2_add_s_gxb( const bmath_hf3_op_ar2_add_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_set_f3( r, 1.0 ); } \
  static inline sz_t bmath_hf3_op_ar2_add_s_get_arity( const bmath_hf3_op_ar2_add_s* o ){ return 2; } \
  static inline void bmath_hf3_op_ar2_add_s_ofx( const bmath_hf3_op_ar2_add_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar2_add_s_fx( o, a[0], a[1], r ); } \
  static inline void bmath_hf3_op_ar2_add_s_ogx( const bmath_hf3_op_ar2_add_s* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ){ if( i == 0 ) { bmath_hf3_op_ar2_add_s_gxa( o, a[0], a[1], r ); } else { bmath_hf3_op_ar2_add_s_gxb( o, a[0], a[1], r ); } }
#define TYPEOF_bmath_hf3_op_ar2_sub_s 2454404100
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar2_sub_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar2_sub_s ) \
    {aware_t _;}; \
  static inline void bmath_hf3_op_ar2_sub_s_fx( const bmath_hf3_op_ar2_sub_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_add( a, b, r ); } \
  static inline void bmath_hf3_op_ar2_sub_s_gxa( const bmath_hf3_op_ar2_sub_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_set_f3( r,  1.0 ); } \
  static inline void bmath_hf3_op_ar2_sub_s_gxb( const bmath_hf3_op_ar2_sub_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_set_f3( r, -1.0 ); } \
  static inline sz_t bmath_hf3_op_ar2_sub_s_get_arity( const bmath_hf3_op_ar2_sub_s* o ){ return 2; } \
  static inline void bmath_hf3_op_ar2_sub_s_ofx( const bmath_hf3_op_ar2_sub_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar2_sub_s_fx( o, a[0], a[1], r ); } \
  static inline void bmath_hf3_op_ar2_sub_s_ogx( const bmath_hf3_op_ar2_sub_s* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ){ if( i == 0 ) { bmath_hf3_op_ar2_sub_s_gxa( o, a[0], a[1], r ); } else { bmath_hf3_op_ar2_sub_s_gxb( o, a[0], a[1], r ); } }
#define TYPEOF_bmath_hf3_op_ar2_hmul_s 3895596320
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar2_hmul_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar2_hmul_s ) \
    {aware_t _;}; \
  static inline void bmath_hf3_op_ar2_hmul_s_fx( const bmath_hf3_op_ar2_hmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_hmul( a, b, r ); } \
  static inline void bmath_hf3_op_ar2_hmul_s_gxa( const bmath_hf3_op_ar2_hmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_cpy( b, r ); } \
  static inline void bmath_hf3_op_ar2_hmul_s_gxb( const bmath_hf3_op_ar2_hmul_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_cpy( a, r ); } \
  static inline sz_t bmath_hf3_op_ar2_hmul_s_get_arity( const bmath_hf3_op_ar2_hmul_s* o ){ return 2; } \
  static inline void bmath_hf3_op_ar2_hmul_s_ofx( const bmath_hf3_op_ar2_hmul_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar2_hmul_s_fx( o, a[0], a[1], r ); } \
  static inline void bmath_hf3_op_ar2_hmul_s_ogx( const bmath_hf3_op_ar2_hmul_s* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ){ if( i == 0 ) { bmath_hf3_op_ar2_hmul_s_gxa( o, a[0], a[1], r ); } else { bmath_hf3_op_ar2_hmul_s_gxb( o, a[0], a[1], r ); } }
#define TYPEOF_bmath_hf3_op_ar2_div_s 2764301237
#define BETH_EXPAND_ITEM_bmath_hf3_op_ar2_div_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_op_ar2_div_s ) \
    {aware_t _;}; \
  static inline void bmath_hf3_op_ar2_div_s_fx( const bmath_hf3_op_ar2_div_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_fp_f3_op_ar2( a, b, ( bmath_fp_f3_op_ar2 )bmath_f3_op_ar2_div_s_fx,  NULL, r ); } \
  static inline void bmath_hf3_op_ar2_div_s_gxa( const bmath_hf3_op_ar2_div_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_fp_f3_op_ar2( a, b, ( bmath_fp_f3_op_ar2 )bmath_f3_op_ar2_div_s_gxa, NULL, r ); } \
  static inline void bmath_hf3_op_ar2_div_s_gxb( const bmath_hf3_op_ar2_div_s* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ){ bmath_hf3_s_fp_f3_op_ar2( a, b, ( bmath_fp_f3_op_ar2 )bmath_f3_op_ar2_div_s_gxb, NULL, r ); } \
  static inline sz_t bmath_hf3_op_ar2_div_s_get_arity( const bmath_hf3_op_ar2_div_s* o ){ return 2; } \
  static inline void bmath_hf3_op_ar2_div_s_ofx( const bmath_hf3_op_ar2_div_s* o, const bmath_hf3_s** a, bmath_hf3_s* r ){ bmath_hf3_op_ar2_div_s_fx( o, a[0], a[1], r ); } \
  static inline void bmath_hf3_op_ar2_div_s_ogx( const bmath_hf3_op_ar2_div_s* o, sz_t i, const bmath_hf3_s** a, bmath_hf3_s* r ){ if( i == 0 ) { bmath_hf3_op_ar2_div_s_gxa( o, a[0], a[1], r ); } else { bmath_hf3_op_ar2_div_s_gxb( o, a[0], a[1], r ); } }
#define BETH_EXPAND_GROUP_bmath_hf3_op_ar2 \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar2 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar2_add_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar2_sub_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar2_hmul_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_op_ar2_div_s ); \
  typedef void (*bmath_hf3_op_ar2_fx)( const bmath_hf3_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  typedef void (*bmath_hf3_op_ar2_gxa)( const bmath_hf3_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  typedef void (*bmath_hf3_op_ar2_gxb)( const bmath_hf3_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ); \
  BCORE_DECLARE_SPECT( bmath_hf3_op_ar2 ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_op_ar2_fx fx; \
      bmath_hf3_op_ar2_gxa gxa; \
      bmath_hf3_op_ar2_gxb gxb; \
  }; \
  static inline bmath_hf3_op_ar2* bmath_hf3_op_ar2_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_op_ar2, t ); return ( bmath_hf3_op_ar2* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_op_ar2_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_op_ar2 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_op_ar2 ) \
  static inline bl_t bmath_hf3_op_ar2_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_op_ar2 ); } \
  static inline void bmath_hf3_op_ar2_a_fx( const bmath_hf3_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ) { bmath_hf3_op_ar2_s_get_aware( o )->fx( o, a, b, r ); } \
  static inline bl_t bmath_hf3_op_ar2_a_defines_fx( const bmath_hf3_op_ar2* o ) { return bmath_hf3_op_ar2_s_get_aware( o )->fx != NULL; } \
  static inline void bmath_hf3_op_ar2_a_gxa( const bmath_hf3_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ) { bmath_hf3_op_ar2_s_get_aware( o )->gxa( o, a, b, r ); } \
  static inline bl_t bmath_hf3_op_ar2_a_defines_gxa( const bmath_hf3_op_ar2* o ) { return bmath_hf3_op_ar2_s_get_aware( o )->gxa != NULL; } \
  static inline void bmath_hf3_op_ar2_a_gxb( const bmath_hf3_op_ar2* o, const bmath_hf3_s* a, const bmath_hf3_s* b, bmath_hf3_s* r ) { bmath_hf3_op_ar2_s_get_aware( o )->gxb( o, a, b, r ); } \
  static inline bl_t bmath_hf3_op_ar2_a_defines_gxb( const bmath_hf3_op_ar2* o ) { return bmath_hf3_op_ar2_s_get_aware( o )->gxb != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar2_add_s \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar2_sub_s \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar2_hmul_s \
  BETH_EXPAND_ITEM_bmath_hf3_op_ar2_div_s

/**********************************************************************************************************************/
// source: bmath_hf3_vm.h

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm

#define TYPEOF_bmath_hf3_vm 1129494905
#define TYPEOF_bmath_hf3_vm_s 4000694131
#define TYPEOF_bmath_hf3_vm_holor_s 3470165822
#define BETH_EXPAND_ITEM_bmath_hf3_vm_holor_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_holor_s ) \
    {aware_t _;tp_t name;tp_t type;bmath_hf3_s hf3;};
#define TYPEOF_bmath_hf3_vm_arr_holor_s 3798245038
#define BETH_EXPAND_ITEM_bmath_hf3_vm_arr_holor_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_arr_holor_s ) \
    {aware_t _;BCORE_ARRAY_DYN_SOLID_STATIC_S( bmath_hf3_vm_holor_s, );}; \
  static inline void bmath_hf3_vm_arr_holor_s_set_space( bmath_hf3_vm_arr_holor_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_vm_arr_holor_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_vm_arr_holor_s_set_size( bmath_hf3_vm_arr_holor_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bmath_hf3_vm_arr_holor_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_vm_arr_holor_s_clear( bmath_hf3_vm_arr_holor_s* o ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_vm_arr_holor_s, ( bcore_array* )o, 0 ); } \
  static inline bmath_hf3_vm_holor_s* bmath_hf3_vm_arr_holor_s_push_c( bmath_hf3_vm_arr_holor_s* o, const bmath_hf3_vm_holor_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_vm_arr_holor_s, ( bcore_array* )o, sr_twc( TYPEOF_bmath_hf3_vm_holor_s, v ) ); return &o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_vm_holor_s* bmath_hf3_vm_arr_holor_s_push_d( bmath_hf3_vm_arr_holor_s* o,       bmath_hf3_vm_holor_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_vm_arr_holor_s, ( bcore_array* )o, sr_tsd( TYPEOF_bmath_hf3_vm_holor_s, v ) ); return &o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_vm_holor_s* bmath_hf3_vm_arr_holor_s_push( bmath_hf3_vm_arr_holor_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bmath_hf3_vm_arr_holor_s, ( bcore_array* )o, sr_null() ); \
      return &o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bmath_hf3_vm_prop_s 103161229
#define BETH_EXPAND_ITEM_bmath_hf3_vm_prop_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_prop_s ) \
    {aware_t _;bmath_hf3_vm_op* op;bmath_hf3_vm_s* p;}; \
  static inline void bmath_hf3_vm_prop_s_copy_x( bmath_hf3_vm_prop_s* o ){ o->p = (bmath_hf3_vm_s*)bmath_hf3_vm_s_get_aware( o->op ); } \
  static inline void bmath_hf3_vm_prop_s_mutated( bmath_hf3_vm_prop_s* o ){ bmath_hf3_vm_prop_s_copy_x( o ); } \
  static inline void bmath_hf3_vm_prop_s_run( const bmath_hf3_vm_prop_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_vm_p_run( o->p, (vc_t)o->op, hbase ); }
#define TYPEOF_bmath_hf3_vm_proc_s 2358437536
#define BETH_EXPAND_ITEM_bmath_hf3_vm_proc_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_proc_s ) \
    {aware_t _;tp_t name;BCORE_ARRAY_DYN_SOLID_STATIC_S( bmath_hf3_vm_prop_s, );bcore_arr_sz_s in;bcore_arr_sz_s out;}; \
  static inline void bmath_hf3_vm_proc_s_run( const bmath_hf3_vm_proc_s* o, bmath_hf3_vm_holor_s* hbase ){ for( sz_t i = 0; i < o->size; i++ ) bmath_hf3_vm_prop_s_run( &o->data[ i ], hbase ); } \
  static inline void bmath_hf3_vm_proc_s_set_space( bmath_hf3_vm_proc_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_vm_proc_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_vm_proc_s_set_size( bmath_hf3_vm_proc_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bmath_hf3_vm_proc_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_vm_proc_s_clear( bmath_hf3_vm_proc_s* o ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_vm_proc_s, ( bcore_array* )o, 0 ); } \
  static inline bmath_hf3_vm_prop_s* bmath_hf3_vm_proc_s_push_c( bmath_hf3_vm_proc_s* o, const bmath_hf3_vm_prop_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_vm_proc_s, ( bcore_array* )o, sr_twc( TYPEOF_bmath_hf3_vm_prop_s, v ) ); return &o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_vm_prop_s* bmath_hf3_vm_proc_s_push_d( bmath_hf3_vm_proc_s* o,       bmath_hf3_vm_prop_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_vm_proc_s, ( bcore_array* )o, sr_tsd( TYPEOF_bmath_hf3_vm_prop_s, v ) ); return &o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_vm_prop_s* bmath_hf3_vm_proc_s_push( bmath_hf3_vm_proc_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bmath_hf3_vm_proc_s, ( bcore_array* )o, sr_null() ); \
      return &o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bmath_hf3_vm_library_s 2474434231
#define BETH_EXPAND_ITEM_bmath_hf3_vm_library_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_library_s ) \
    {aware_t _;BCORE_ARRAY_DYN_SOLID_STATIC_S( bmath_hf3_vm_proc_s, );}; \
  static inline void bmath_hf3_vm_library_s_set_space( bmath_hf3_vm_library_s* o, sz_t size ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_vm_library_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_vm_library_s_set_size( bmath_hf3_vm_library_s* o, sz_t size ) { bcore_array_t_set_size( TYPEOF_bmath_hf3_vm_library_s, ( bcore_array* )o, size ); } \
  static inline void bmath_hf3_vm_library_s_clear( bmath_hf3_vm_library_s* o ) { bcore_array_t_set_space( TYPEOF_bmath_hf3_vm_library_s, ( bcore_array* )o, 0 ); } \
  static inline bmath_hf3_vm_proc_s* bmath_hf3_vm_library_s_push_c( bmath_hf3_vm_library_s* o, const bmath_hf3_vm_proc_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_vm_library_s, ( bcore_array* )o, sr_twc( TYPEOF_bmath_hf3_vm_proc_s, v ) ); return &o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_vm_proc_s* bmath_hf3_vm_library_s_push_d( bmath_hf3_vm_library_s* o,       bmath_hf3_vm_proc_s* v ) { bcore_array_t_push( TYPEOF_bmath_hf3_vm_library_s, ( bcore_array* )o, sr_tsd( TYPEOF_bmath_hf3_vm_proc_s, v ) ); return &o->data[ o->size - 1 ]; } \
  static inline bmath_hf3_vm_proc_s* bmath_hf3_vm_library_s_push( bmath_hf3_vm_library_s* o ) \
  { \
      bcore_array_t_push( TYPEOF_bmath_hf3_vm_library_s, ( bcore_array* )o, sr_null() ); \
      return &o->data[ o->size - 1 ]; \
  }
#define TYPEOF_bmath_hf3_vm_frame_s 1174748325
#define BETH_EXPAND_ITEM_bmath_hf3_vm_frame_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_frame_s ) \
    {aware_t _;bmath_hf3_vm_arr_holor_s arr_holor;bmath_hf3_vm_library_s library;tp_t proc_setup;tp_t proc_shelve;bcore_hmap_tpuz_s map_proc;bcore_hmap_tpuz_s map_holor;bcore_hmap_name_s map_name;}; \
  void bmath_hf3_vm_frame_s_setup( bmath_hf3_vm_frame_s* o ); \
  static inline void bmath_hf3_vm_frame_s_mutated( bmath_hf3_vm_frame_s* o ){ bmath_hf3_vm_frame_s_setup( o ); } \
  void bmath_hf3_vm_frame_s_shelve( bmath_hf3_vm_frame_s* o );
#define BETH_EXPAND_GROUP_bmath_hf3_vm \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_holor_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_arr_holor_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_prop_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_proc_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_library_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_frame_s ); \
  typedef void (*bmath_hf3_vm_run)( const bmath_hf3_vm* o, bmath_hf3_vm_holor_s* hbase ); \
  BCORE_DECLARE_SPECT( bmath_hf3_vm ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_vm_run run; \
  }; \
  static inline bmath_hf3_vm* bmath_hf3_vm_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_vm, t ); return ( bmath_hf3_vm* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_vm_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_vm ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_vm ) \
  static inline bl_t bmath_hf3_vm_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_vm ); } \
  BETH_EXPAND_ITEM_bmath_hf3_vm_holor_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_arr_holor_s \
  static inline void bmath_hf3_vm_p_run( const bmath_hf3_vm_s* __p, const bmath_hf3_vm* o, bmath_hf3_vm_holor_s* hbase ) { __p->run( o, hbase ); } \
  static inline void bmath_hf3_vm_a_run( const bmath_hf3_vm* o, bmath_hf3_vm_holor_s* hbase ) { bmath_hf3_vm_s_get_aware( o )->run( o, hbase ); } \
  static inline bl_t bmath_hf3_vm_p_defines_run( const bmath_hf3_vm_s* __p ) { return __p->run != NULL; } \
  static inline bl_t bmath_hf3_vm_a_defines_run( const bmath_hf3_vm* o ) { return bmath_hf3_vm_s_get_aware( o )->run != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_vm_prop_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_proc_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_library_s \
  BETH_EXPAND_GROUP_bmath_hf3_vm_op \
  BETH_EXPAND_ITEM_bmath_hf3_vm_frame_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op

#define TYPEOF_bmath_hf3_vm_op 1856140757
#define TYPEOF_bmath_hf3_vm_op_s 1119490359
#define BETH_EXPAND_GROUP_bmath_hf3_vm_op \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2 ); \
  BETH_EXPAND_GROUP_bmath_hf3_vm_op_ar0 \
  BETH_EXPAND_GROUP_bmath_hf3_vm_op_ar1 \
  BETH_EXPAND_GROUP_bmath_hf3_vm_op_ar2

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op_ar0

#define TYPEOF_bmath_hf3_vm_op_ar0 2688961127
#define TYPEOF_bmath_hf3_vm_op_ar0_s 1403220289
#define TYPEOF_bmath_hf3_vm_op_ar0_determine_s 4104539495
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar0_determine_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar0_determine_s ) \
    {aware_t _;sz_t a;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_determine_s_csetup( bmath_hf3_vm_op_ar0_determine_s* o, sz_t idx_a ){ if( !o ) o = bmath_hf3_vm_op_ar0_determine_s_create(); o->a = idx_a; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar0_determine_s_run( const bmath_hf3_vm_op_ar0_determine_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_fit_v_size( &hbase[ o->a ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_determine_s_set_args( bmath_hf3_vm_op_ar0_determine_s* o, sz_t idx_a ){ o->a = idx_a; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar0_vacate_s 654152524
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar0_vacate_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar0_vacate_s ) \
    {aware_t _;sz_t a;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_vacate_s_csetup( bmath_hf3_vm_op_ar0_vacate_s* o, sz_t idx_a ){ if( !o ) o = bmath_hf3_vm_op_ar0_vacate_s_create(); o->a = idx_a; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar0_vacate_s_run( const bmath_hf3_vm_op_ar0_vacate_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_set_vacant( &hbase[ o->a ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_vacate_s_set_args( bmath_hf3_vm_op_ar0_vacate_s* o, sz_t idx_a ){ o->a = idx_a; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar0_randomize_s 2304548753
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar0_randomize_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar0_randomize_s ) \
    {aware_t _;sz_t a;u2_t rseed;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_randomize_s_csetup_randomize( bmath_hf3_vm_op_ar0_randomize_s* o, sz_t idx_a, u2_t rseed ){ if( !o ) o = bmath_hf3_vm_op_ar0_randomize_s_create(); o->a = idx_a; o->rseed = rseed; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar0_randomize_s_run( const bmath_hf3_vm_op_ar0_randomize_s* o, bmath_hf3_vm_holor_s* hbase ){ u2_t rval = o->rseed + o->a; bmath_hf3_s_set_random( &hbase[ o->a ].hf3, 1.0, -1.0, 1.0, &rval ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_randomize_s_set_args( bmath_hf3_vm_op_ar0_randomize_s* o, sz_t idx_a ){ o->a = idx_a; return (bmath_hf3_vm_op*)o; }
#define BETH_EXPAND_GROUP_bmath_hf3_vm_op_ar0 \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar0 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar0_determine_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar0_vacate_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar0_randomize_s ); \
  typedef bmath_hf3_vm_op* (*bmath_hf3_vm_op_ar0_set_args)( bmath_hf3_vm_op_ar0* o, sz_t idx_a ); \
  BCORE_DECLARE_SPECT( bmath_hf3_vm_op_ar0 ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_vm_op_ar0_set_args set_args; \
  }; \
  static inline bmath_hf3_vm_op_ar0* bmath_hf3_vm_op_ar0_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_vm_op_ar0, t ); return ( bmath_hf3_vm_op_ar0* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_vm_op_ar0_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_vm_op_ar0 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_vm_op_ar0 ) \
  static inline bl_t bmath_hf3_vm_op_ar0_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_vm_op_ar0 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar0_a_set_args( bmath_hf3_vm_op_ar0* o, sz_t idx_a ) { return bmath_hf3_vm_op_ar0_s_get_aware( o )->set_args( o, idx_a ); } \
  static inline bl_t bmath_hf3_vm_op_ar0_a_defines_set_args( const bmath_hf3_vm_op_ar0* o ) { return bmath_hf3_vm_op_ar0_s_get_aware( o )->set_args != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar0_determine_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar0_vacate_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar0_randomize_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op_ar1

#define TYPEOF_bmath_hf3_vm_op_ar1 2672183508
#define TYPEOF_bmath_hf3_vm_op_ar1_s 3598431494
#define TYPEOF_bmath_hf3_vm_op_ar1_linear_s 4142029110
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar1_linear_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar1_linear_s ) \
    {aware_t _;sz_t a;sz_t b;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_linear_s_csetup( bmath_hf3_vm_op_ar1_linear_s* o, sz_t idx_a, sz_t idx_b ){ if( !o ) o = bmath_hf3_vm_op_ar1_linear_s_create(); o->a = idx_a; o->b = idx_b; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar1_linear_s_run( const bmath_hf3_vm_op_ar1_linear_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_cpy( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_linear_s_set_args( bmath_hf3_vm_op_ar1_linear_s* o, sz_t idx_a, sz_t idx_b ){ o->a = idx_a; o->b = idx_b; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar1_tanh_s 2288459742
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar1_tanh_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar1_tanh_s ) \
    {aware_t _;sz_t a;sz_t b;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_tanh_s_csetup( bmath_hf3_vm_op_ar1_tanh_s* o, sz_t idx_a, sz_t idx_b ){ if( !o ) o = bmath_hf3_vm_op_ar1_tanh_s_create(); o->a = idx_a; o->b = idx_b; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar1_tanh_s_run( const bmath_hf3_vm_op_ar1_tanh_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_tanh( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_tanh_s_set_args( bmath_hf3_vm_op_ar1_tanh_s* o, sz_t idx_a, sz_t idx_b ){ o->a = idx_a; o->b = idx_b; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar1_unary_s 3629169270
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar1_unary_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar1_unary_s ) \
    {aware_t _;sz_t a;sz_t b;bmath_fp_f3_ar1 unary;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_unary_s_csetup( bmath_hf3_vm_op_ar1_unary_s* o, sz_t idx_a, sz_t idx_b ){ if( !o ) o = bmath_hf3_vm_op_ar1_unary_s_create(); o->a = idx_a; o->b = idx_b; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar1_unary_s_run( const bmath_hf3_vm_op_ar1_unary_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_fp_f3_ar1( &hbase[ o->a ].hf3, o->unary, &hbase[ o->b ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_unary_s_set_args( bmath_hf3_vm_op_ar1_unary_s* o, sz_t idx_a, sz_t idx_b ){ o->a = idx_a; o->b = idx_b; return (bmath_hf3_vm_op*)o; }
#define BETH_EXPAND_GROUP_bmath_hf3_vm_op_ar1 \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar1 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar1_linear_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar1_tanh_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar1_unary_s ); \
  typedef bmath_hf3_vm_op* (*bmath_hf3_vm_op_ar1_set_args)( bmath_hf3_vm_op_ar1* o, sz_t idx_a, sz_t idx_b ); \
  BCORE_DECLARE_SPECT( bmath_hf3_vm_op_ar1 ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_vm_op_ar1_set_args set_args; \
  }; \
  static inline bmath_hf3_vm_op_ar1* bmath_hf3_vm_op_ar1_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_vm_op_ar1, t ); return ( bmath_hf3_vm_op_ar1* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_vm_op_ar1_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_vm_op_ar1 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_vm_op_ar1 ) \
  static inline bl_t bmath_hf3_vm_op_ar1_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_vm_op_ar1 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar1_a_set_args( bmath_hf3_vm_op_ar1* o, sz_t idx_a, sz_t idx_b ) { return bmath_hf3_vm_op_ar1_s_get_aware( o )->set_args( o, idx_a, idx_b ); } \
  static inline bl_t bmath_hf3_vm_op_ar1_a_defines_set_args( const bmath_hf3_vm_op_ar1* o ) { return bmath_hf3_vm_op_ar1_s_get_aware( o )->set_args != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar1_linear_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar1_tanh_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar1_unary_s

//----------------------------------------------------------------------------------------------------------------------
// group: bmath_hf3_vm_op_ar2

#define TYPEOF_bmath_hf3_vm_op_ar2 2722516365
#define TYPEOF_bmath_hf3_vm_op_ar2_s 647003007
#define TYPEOF_bmath_hf3_vm_op_ar2_add_s 3730884903
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_add_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_add_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_add_s_csetup( bmath_hf3_vm_op_ar2_add_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_add_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_add_s_run( const bmath_hf3_vm_op_ar2_add_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_add( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_add_s_set_args( bmath_hf3_vm_op_ar2_add_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_sub_s 3169546886
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_sub_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_sub_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_sub_s_csetup( bmath_hf3_vm_op_ar2_sub_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_sub_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_sub_s_run( const bmath_hf3_vm_op_ar2_sub_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_sub( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_sub_s_set_args( bmath_hf3_vm_op_ar2_sub_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_bmul_s 999346868
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_bmul_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_bmul_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_bmul_s_csetup( bmath_hf3_vm_op_ar2_bmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_bmul_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_bmul_s_run( const bmath_hf3_vm_op_ar2_bmul_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_bmul( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_bmul_s_set_args( bmath_hf3_vm_op_ar2_bmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_bmul_htp_s 2918645955
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_bmul_htp_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_bmul_htp_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_bmul_htp_s_csetup( bmath_hf3_vm_op_ar2_bmul_htp_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_bmul_htp_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_bmul_htp_s_run( const bmath_hf3_vm_op_ar2_bmul_htp_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_bmul_htp( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_bmul_htp_s_set_args( bmath_hf3_vm_op_ar2_bmul_htp_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_htp_bmul_s 2976214885
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_htp_bmul_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_htp_bmul_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_htp_bmul_s_csetup( bmath_hf3_vm_op_ar2_htp_bmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_htp_bmul_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_htp_bmul_s_run( const bmath_hf3_vm_op_ar2_htp_bmul_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_htp_bmul( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_htp_bmul_s_set_args( bmath_hf3_vm_op_ar2_htp_bmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_htp_bmul_htp_s 444361642
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_htp_bmul_htp_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_htp_bmul_htp_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_htp_bmul_htp_s_csetup( bmath_hf3_vm_op_ar2_htp_bmul_htp_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_htp_bmul_htp_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_htp_bmul_htp_s_run( const bmath_hf3_vm_op_ar2_htp_bmul_htp_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_htp_bmul_htp( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_htp_bmul_htp_s_set_args( bmath_hf3_vm_op_ar2_htp_bmul_htp_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_hmul_s 539157526
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_hmul_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_hmul_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_hmul_s_csetup( bmath_hf3_vm_op_ar2_hmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_hmul_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_hmul_s_run( const bmath_hf3_vm_op_ar2_hmul_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_hmul( &hbase[ o->a ].hf3, &hbase[ o->b ].hf3, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_hmul_s_set_args( bmath_hf3_vm_op_ar2_hmul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_mul_scl_s 3524807431
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_mul_scl_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_mul_scl_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_mul_scl_s_csetup( bmath_hf3_vm_op_ar2_mul_scl_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_mul_scl_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_mul_scl_s_run( const bmath_hf3_vm_op_ar2_mul_scl_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_mul_scl( &hbase[ o->a ].hf3, hbase[ o->b ].hf3.v_data, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_mul_scl_s_set_args( bmath_hf3_vm_op_ar2_mul_scl_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define TYPEOF_bmath_hf3_vm_op_ar2_scl_mul_s 949070651
#define BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_scl_mul_s \
  BCORE_DECLARE_OBJECT( bmath_hf3_vm_op_ar2_scl_mul_s ) \
    {aware_t _;sz_t a;sz_t b;sz_t c;}; \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_scl_mul_s_csetup( bmath_hf3_vm_op_ar2_scl_mul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ if( !o ) o = bmath_hf3_vm_op_ar2_scl_mul_s_create(); o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; } \
  static inline void bmath_hf3_vm_op_ar2_scl_mul_s_run( const bmath_hf3_vm_op_ar2_scl_mul_s* o, bmath_hf3_vm_holor_s* hbase ){ bmath_hf3_s_mul_scl( &hbase[ o->b ].hf3, hbase[ o->a ].hf3.v_data, &hbase[ o->c ].hf3 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_scl_mul_s_set_args( bmath_hf3_vm_op_ar2_scl_mul_s* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ){ o->a = idx_a; o->b = idx_b; o->c = idx_c; return (bmath_hf3_vm_op*)o; }
#define BETH_EXPAND_GROUP_bmath_hf3_vm_op_ar2 \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2 ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_add_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_sub_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_bmul_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_bmul_htp_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_htp_bmul_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_htp_bmul_htp_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_hmul_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_mul_scl_s ); \
  BCORE_FORWARD_OBJECT( bmath_hf3_vm_op_ar2_scl_mul_s ); \
  typedef bmath_hf3_vm_op* (*bmath_hf3_vm_op_ar2_set_args)( bmath_hf3_vm_op_ar2* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ); \
  BCORE_DECLARE_SPECT( bmath_hf3_vm_op_ar2 ) \
  { \
      bcore_spect_header_s header; \
      bmath_hf3_vm_op_ar2_set_args set_args; \
  }; \
  static inline bmath_hf3_vm_op_ar2* bmath_hf3_vm_op_ar2_t_create( tp_t t ) { bcore_trait_assert_satisfied_type( TYPEOF_bmath_hf3_vm_op_ar2, t ); return ( bmath_hf3_vm_op_ar2* )bcore_inst_t_create( t ); } \
  static inline bl_t bmath_hf3_vm_op_ar2_t_is_trait_of( tp_t t ) { return bcore_trait_is_of( t, TYPEOF_bmath_hf3_vm_op_ar2 ); } \
  BCORE_DECLARE_VIRTUAL_AWARE_OBJECT( bmath_hf3_vm_op_ar2 ) \
  static inline bl_t bmath_hf3_vm_op_ar2_a_is_trait_of( vc_t o ) { return bcore_trait_is_of( o ? *(aware_t*)o : 0, TYPEOF_bmath_hf3_vm_op_ar2 ); } \
  static inline bmath_hf3_vm_op* bmath_hf3_vm_op_ar2_a_set_args( bmath_hf3_vm_op_ar2* o, sz_t idx_a, sz_t idx_b, sz_t idx_c ) { return bmath_hf3_vm_op_ar2_s_get_aware( o )->set_args( o, idx_a, idx_b, idx_c ); } \
  static inline bl_t bmath_hf3_vm_op_ar2_a_defines_set_args( const bmath_hf3_vm_op_ar2* o ) { return bmath_hf3_vm_op_ar2_s_get_aware( o )->set_args != NULL; } \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_add_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_sub_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_bmul_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_bmul_htp_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_htp_bmul_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_htp_bmul_htp_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_hmul_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_mul_scl_s \
  BETH_EXPAND_ITEM_bmath_hf3_vm_op_ar2_scl_mul_s

/**********************************************************************************************************************/

vd_t bmath_planted_signal_handler( const bcore_signal_s* o );

#endif // BMATH_PLANTED_H
