/** This file was generated by the beth-plant-compiler.
 *
 *  Copyright and License:
 *    Generated code inherits the copyright and license of the beth-plant source code.
 *    The following files contain all source code related to this file:
 *    bhvm_hf3.h
 *
 */

#include "bhvm_planted.h"
#include "bcore_spect.h"
#include "bcore_spect_inst.h"
#include "bcore_sr.h"
#include "bcore_const_manager.h"


/**********************************************************************************************************************/
// source: bhvm_hf3.h
#include "bhvm_hf3.h"

//----------------------------------------------------------------------------------------------------------------------
// group: bhvm_hf3

BCORE_DEFINE_OBJECT_INST_P( bhvm_hf3_s )
"aware bcore_inst"
"{"
    "sz_t [] d;"
    "f3_t [] v;"
"}";

BCORE_DEFINE_OBJECT_INST_P( bhvm_hf3_adl_s )
"aware bcore_array"
"{"
    "bhvm_hf3_s => [];"
"}";

/**********************************************************************************************************************/

vd_t bhvm_planted_signal_handler( const bcore_signal_s* o )
{
    switch( bcore_signal_s_handle_type( o, typeof( "bhvm_planted" ) ) )
    {
        case TYPEOF_init1:
        {
            // Comment or remove line below to rebuild this target.
            bcore_const_x_set_d( typeof( "bhvm_planted_hash" ), sr_tp( 4142767635 ) );
            BCORE_REGISTER_OBJECT( bhvm_hf3_s );
            BCORE_REGISTER_OBJECT( bhvm_hf3_adl_s );
            BCORE_REGISTER_TRAIT( bhvm_hf3, bcore_inst );
        }
        break;
        default: break;
    }
    return NULL;
}
